In [5]:
import pandas as pd

In [15]:
data1 = pd.read_csv("../data/Metadata_Country_API_NY.GDP.MKTP.KD.ZG_DS2_en_csv_v2_121708.csv")
data2 = pd.read_csv("../data/Metadata_Indicator_API_NY.GDP.MKTP.KD.ZG_DS2_en_csv_v2_121708.csv")
data3 = pd.read_csv("../data/API_NY.GDP.MKTP.KD.ZG_DS2_en_csv_v2_121708.csv", skiprows = 4)

In [ ]:
data1.head()

,Country Code,Region,IncomeGroup,SpecialNotes,TableName,Unnamed: 5
0,ABW,Latin America & Caribbean,High income,NaN,Aruba,NaN
1,AFE,NaN,NaN,"26 countries, stretching from the Red Sea in t...",Africa Eastern and Southern,NaN
2,AFG,Middle East & North Africa,Low income,The reporting period for national accounts dat...,Afghanistan,NaN
3,AFW,NaN,NaN,"22 countries, stretching from the westernmost ...",Africa Western and Central,NaN
4,AGO,Sub-Saharan Africa,Lower middle income,The World Bank systematically assesses the app...,Angola,NaN

In [16]:
data2.head()

,INDICATOR_CODE,INDICATOR_NAME,SOURCE_NOTE,SOURCE_ORGANIZATION,Unnamed: 4
0,NY.GDP.MKTP.KD.ZG,GDP growth (annual %),Gross domestic product is the total income ear...,"Country official statistics, National Statisti...",NaN

In [17]:
data3.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2017,2018,2019,2020,2021,2022,2023,2024,2025,Unnamed: 70
0,Aruba,ABW,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,3.493430,3.212471,1.225112,-23.897990,14.730616,10.636431,7.706798,6.810777,NaN,NaN
1,Africa Eastern and Southern,AFE,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,0.418937,7.937038,5.623764,4.649241,5.138168,...,2.677524,2.705194,2.030077,-2.817572,4.578772,3.722717,1.931160,2.763839,NaN,NaN
2,Afghanistan,AFG,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,2.647003,1.189228,3.911603,-2.351101,-20.738839,-6.240172,2.266944,NaN,NaN,NaN
3,Africa Western and Central,AFW,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,1.869593,3.726090,7.038388,5.364089,4.105339,...,2.296349,2.904664,3.281683,-3.730630,2.549691,4.472795,3.662428,4.585674,NaN,NaN
4,Angola,AGO,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,-0.149396,-0.594411,-0.204680,-4.042447,2.102753,4.216003,1.263308,4.423907,NaN,NaN

In [27]:
exc = pd.read_csv("../data/API_PA.NUS.FCRF_DS2_en_csv_v2_121619.csv", skiprows = 1)

In [34]:
exc.head()

,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,Last Updated Date,2026-04-08,Unnamed: 2
Country Name,Country Code,Indicator Name,Indicator Code,1960.000000,1961.000000,1962.000000,1963.000000,1964.000000,1965.000000,1966.000000,1967.000000,1968.000000,1969.000000,1970.000000,1971.000000,1972.000000,1973.000000,1974.000000,1975.000000,1976.000000,1977.000000,1978.000000,1979.000000,1980.000000,1981.000000,1982.000000,1983.000000,1984.000000,1985.000000,1986.000000,1987.000000,1988.000000,1989.000000,1990.000000,1991.000000,1992.000000,1993.000000,1994.000000,1995.000000,1996.000000,1997.000000,1998.00,1999.000000,2000.000000,2001.000000,2002.000,2003.000000,2004.000000,2005.000000,2006.000000,2007.000000,2.008000e+03,2009.000000,2010.000000,2011.000000,2012.000000,2013.000000,2014.000000,2015.000000,2016.000000,2017.000000,2018.000000,2019.000000,2020.000000,2.021000e+03,2022.00,2023.00,2024.00,2025.0,NaN
Aruba,ABW,"Official exchange rate (LCU per US$, period average)",PA.NUS.FCRF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.790000,1.790000,1.790000,1.790000,1.790000,1.790000,1.790000,1.790000,1.790000,1.790000,1.790000,1.790000,1.79,1.790000,1.790000,1.790000,1.790,1.790000,1.790000,1.790000,1.790000,1.790000,1.790000e+00,1.790000,1.790000,1.790000,1.790000,1.790000,1.790000,1.790000,1.790000,1.790000,1.790000,1.790000,1.790000,1.790000e+00,1.79,1.79,1.79,NaN,NaN
Africa Eastern and Southern,AFE,"Official exchange rate (LCU per US$, period average)",PA.NUS.FCRF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Afghanistan,AFG,"Official exchange rate (LCU per US$, period average)",PA.NUS.FCRF,17.196561,17.196561,17.196561,35.109645,38.692262,38.692262,38.692262,38.692262,38.692262,38.692262,38.692262,38.692262,38.692262,38.692262,38.378709,34.929631,34.929631,34.929631,34.929631,33.846164,34.369458,38.561659,39.276429,39.276429,39.276429,39.276429,39.276429,39.276429,39.276429,39.276429,39.276429,39.276429,39.276429,39.276429,38.818463,36.567145,47.500000,47.500000,47.50,46.619531,47.357575,47.500015,47.263,48.762754,47.845312,49.494597,49.925331,49.962018,5.024961e+01,50.325000,46.452461,46.747008,50.921400,55.377500,57.247500,61.143462,67.866086,68.026904,72.083247,77.737949,76.813536,NaN,NaN,NaN,NaN,NaN,NaN
Africa Western and Central,AFW,"Official exchange rate (LCU per US$, period average)",PA.NUS.FCRF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [50]:
data5 = pd.read_excel("../data/CMO-Historical-Data-Annual.xlsx")

In [49]:
data5.head()

Empty DataFrame
Columns: []
Index: []

In [56]:
file = "../data/CMO-Historical-Data-Annual.xlsx"

xls = pd.ExcelFile(file, engine="openpyxl")
print(xls.sheet_names)

['AFOSHEET', 'Annual Prices (Nominal)', 'Annual Indices (Nominal)', 'Annual Prices (Real)', 'Annual Indices (Real)', 'Description', 'Definitions', 'Index Weights']

In [63]:
data5 = pd.read_excel(file, sheet_name = "Annual Prices (Nominal)", skiprows = 6, engine="openpyxl")

In [64]:
data5.head(10)

,Unnamed: 0,"Crude oil, average","Crude oil, Brent","Crude oil, Dubai","Crude oil, WTI","Coal, Australian","Coal, South African","Natural gas, US","Natural gas, Europe","Liquefied natural gas, Japan",...,Aluminum,"Iron ore, cfr spot",Copper,Lead,Tin,Nickel,Zinc,Gold,Platinum,Silver
0,NaN,($/bbl),($/bbl),($/bbl),($/bbl),($/mt),($/mt),($/mmbtu),($/mmbtu),($/mmbtu),...,($/mt),($/dmtu),($/mt),($/mt),($/mt),($/mt),($/mt),($/troy oz),($/troy oz),($/troy oz)
1,1960.0,1.63,1.63,1.63,…,…,…,0.14,0.404774,…,...,511.471832,11.42,678.755833,198.85,2196.733333,1631,246.191667,35.27,83.5,0.9137
2,1961.0,1.57,1.57,1.57,…,…,…,0.15,0.404774,…,...,511.471832,11.02,633.084167,176.975,2449.891667,1711,214.308333,35.25,83.5,0.924442
3,1962.0,1.52,1.52,1.52,…,…,…,0.16,0.404774,…,...,498.060392,11.01,645.143333,155.283333,2471.383333,1761,185.925,35.23,83.5,1.083725
4,1963.0,1.5,1.5,1.5,…,…,…,0.16,0.391351,…,...,498.795265,11.02,645.950833,174.808333,2507.733333,1741.666667,211.508333,35.09,80.930833,1.279108
5,1964.0,1.45,1.45,1.45,…,…,…,0.15,0.38415,…,...,525.985631,10.24,969.753333,277.883333,3412.741667,1741.666667,326.491667,35.1,88.480833,1.293
6,1965.0,1.42,1.42,1.42,…,…,…,0.16,0.410766,…,...,540.131836,10.661667,1292.844167,317.175,3890.783333,1735,311.25,35.12,98.041667,1.293
7,1966.0,1.36,1.36,1.36,…,…,…,0.16,0.424929,…,...,540.131836,9.52,1531.513333,260.65,3573.508333,1739,281.108333,35.13,99.720833,1.293
8,1967.0,1.33,1.33,1.33,…,…,…,0.16,0.456647,…,...,540.131836,8.86,1134.7725,227.675,3308.025,1935.7,273.333333,34.95,110.248333,1.549183
9,1968.0,1.32,1.32,1.32,…,…,…,0.16,0.451802,…,...,552.992086,8.77,1241.9525,240.491667,3126.883333,2074.5,262.891667,38.925,117.208333,2.144633

In [72]:
data5[["Unnamed: 0", "Copper"]].describe()

        Unnamed: 0
count    66.000000
mean   1992.500000
std      19.196354
min    1960.000000
25%    1976.250000
50%    1992.500000
75%    2008.750000
max    2025.000000

In [76]:
debt = pd.read_csv("../data/API_ZMB_DS2_en_csv_v2_11698.csv", skiprows=3)

In [80]:
debt.columns

Index(['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code',
       '1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968',
       '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977',
       '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986',
       '1987', '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995',
       '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004',
       '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013',
       '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022',
       '2023', '2024', '2025', 'Unnamed: 70'],
      dtype='str')

In [78]:
debt['Indicator Name'].unique()

<StringArray>
[                                                                            'Intentional homicides (per 100,000 people)',
                 'Internally displaced persons, new displacement associated with conflict and violence (number of cases)',
                                      'Voice and Accountability: Percentile Rank, Lower Bound of 90% Confidence Interval',
                                                                      'Travel services (% of commercial service exports)',
                                                                               'Commercial service exports (current US$)',
                                                             'Merchandise exports by the reporting economy (current US$)',
 'Merchandise exports to low- and middle-income economies in Middle East & North Africa (% of total merchandise exports)',
                'Merchandise exports to low- and middle-income economies outside region (% of total merchandise exports)',
                                                                     'Ores and metals exports (% of merchandise exports)',
                                                                                'Fuel exports (% of merchandise exports)',
 ...
                                                             'Foreign direct investment, net outflows (BoP, current US$)',
                                              'Charges for the use of intellectual property, payments (BoP, current US$)',
                                                                       'Imports of goods and services (BoP, current US$)',
                                                                                          'Cereal yield (kg per hectare)',
                                                                                'Crop production index (2014-2016 = 100)',
                                                                                                     'Land area (sq. km)',
                                                                                                   'Forest area (sq. km)',
                                               'Rural land area where elevation is below 5 meters (% of total land area)',
                                                                                           'Arable land (% of land area)',
                                                                                             'Agricultural land (sq. km)']
Length: 1516, dtype: str